// Shared TypeScript types for Trading Laboratory

export type Market = 'crypto' | 'us-futures' | 'kr-futures';
export type DataSource = 'binance' | 'alphavantage' | 'krx';
export type Timeframe = '1m' | '5m' | '1h' | 'day' | 'week';
export type Indicator = 'RSI' | 'MACD' | '20MA' | '50MA' | 'volume' | 'order-book';
export type PropFirmRuleName =
  | 'Daily Loss Limit'
  | 'Max Loss'
  | 'Profit Target'
  | 'Time Limit'
  | 'Consistency';
export type ExperimentStatus = 'pending' | 'running' | 'complete' | 'failed';
export type SetupCategory = 'time' | 'indicator' | 'price';

export interface PropFirmRule {
  name: PropFirmRuleName;
  enabled: boolean;
  description?: string;
}

export interface ExperimentConfig {
  market: Market;
  dataSource: DataSource;
  symbol: string;
  dateRange: {
    start: string; // ISO date string e.g. '2024-01-01'
    end: string;   // ISO date string e.g. '2024-03-31'
  };
  timeframes: Timeframe[];
  indicators: Indicator[];
  propFirmRules: PropFirmRule[];
}

export interface Setup {
  /** Label: 'A', 'B', or 'C' */
  name: string;
  /** Natural language description of the setup entry condition */
  naturalLanguage: string;
  /** Categorization of the condition */
  categories: SetupCategory[];
  /** Allocation percentage of total capital, e.g. 40 for 40% */
  allocationPct: number;
  /** Natural language description of stop-loss logic */
  stopLossLogic: string;
  /** Agent reasoning for this setup */
  reasoning: string;
}

export interface Strategy {
  setups: Setup[];
  /** Overall agent reasoning across all setups */
  overallReasoning: string;
  /**
   * True if the agent returned a total allocation > 100% and the system
   * proportionally normalised the allocations to sum to 100%.
   */
  allocationNormalized?: boolean;
}

export interface RuleAssessment {
  ruleName: PropFirmRuleName;
  /** 'pass' | 'fail' | 'partial' */
  result: 'pass' | 'fail' | 'partial';
  note: string;
}

export interface EvaluationResult {
  /** 0–100: how well the strategy adheres to prop firm rules */
  complianceScore: number;
  /** 0–100: quality of risk management in setups */
  riskQualityScore: number;
  /** 0–100: clarity and actionability of natural language descriptions */
  clarityScore: number;
  /** Weighted composite: (compliance × 0.5) + (riskQuality × 0.3) + (clarity × 0.2) */
  compositeScore: number;
  perRuleAssessment: RuleAssessment[];
  /** True if generated by a mock evaluation agent (not a real compliance check) */
  isMock: boolean;
}

export interface Candle {
  timestamp: number; // Unix ms
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}

export interface ComputedIndicators {
  rsi?: number[];
  macd?: { macd: number[]; signal: number[]; histogram: number[] };
  ma20?: number[];
  ma50?: number[];
}

export interface MarketData {
  symbol: string;
  timeframe: Timeframe;
  candles: Candle[];
  indicators: ComputedIndicators;
}

export interface Experiment {
  id: string;
  name: string;
  status: ExperimentStatus;
  config: ExperimentConfig;
  strategy?: Strategy;
  evaluation?: EvaluationResult;
  executionLog?: string;
  createdAt: number; // Unix ms
  completedAt?: number; // Unix ms
}
